### ISSUE TITLE
Passing Input parameters of HANA to odxl

### ISSUE THREAD

**Issue by joel-myworld** [just-bi/odxl#40]
I've been trying to download data from a calculation view to xlsx format.
But no matter what I do, I cannot pass the input parameters of the calculation view to ODXL.

Can we have support for this in the future?

Keep up the good work!
Cheers,
Joel

**Comment by rpbouman** [comment]
Joel, sounds like a great feature!

In the interest of delivering something quickly, that is not too hard to implement, I suggest we add a $parameters query option which we use to pass them. Sounds good?

**Comment by rpbouman** [comment]
@joel-myworld  actually, upon inspection, it seems the feature is already there. 

If I create a very simple view on DUMMY with one parameter IP_TEST, and then select that paramter in a calculated column, I can do:

http://hanahost:hanaport/system-local/public/rbouman/odxl/service/odxl.xsjs/%22_SYS_BIC%22/%22system-local.public.rbouman.hxmla.models/CA_DUMM_PARAMETERS_GRA_001%22(IP_TEST='bla')?$format=sql

And this is the SQL that is generated: 

SELECT
*
FROM
"_SYS_BIC"."system-local.public.rbouman.hxmla.models/CA_DUMM_PARAMETERS_GRA_001"('PLACEHOLDER' = ('$$IP_TEST$$', 'bla'))

It executes too, and gives me the expected result.

So, since the functionality is already there, we should probably keep it that way. 

The question now is, 
- what does your view look like, 
- how does it define its parameters
- how do you call ODXL
- what is the output of odxl if you specify $format=sql (i.e. what SQL does that generate)
- can you execute that SQL inside HANA studio or webide?
- what happens if you specify $format=csv, what output or error message do you get?

**Comment by joel-myworld** [comment]
@rpbouman I did try something similar. but I didn't have the syntax right. Now I get the SQL query as you mentioned above.

**Comment by rpbouman** [comment]
@joel-myworld Is your issue solved? Can I close this issue?

**Comment by joel-myworld** [comment]
Yes. Thank you.
